DROP TABLE IF EXISTS `member`;
CREATE TABLE  `member` (
  `no` varchar(20) NOT NULL default '',
  `user_id` int(11) NOT NULL auto_increment,
  `id` varchar(255) default NULL,
  `ps` varchar(255) default NULL,
  `handle` text,
  `mail` varchar(255) default NULL,
  `usrmail` varchar(255) default NULL,
  `usrname` text,
  `age` int(11) default NULL,
  `gender` int(11) default NULL,
  `zip` text,
  `pref` int(11) default NULL,
  `addr1` text,
  `addr2` text,
  `attribute` int(11) default NULL,
  `income` int(11) default NULL,
  `bbsmail` int(11) default NULL,
  `institution` int(11) default NULL,
  `mailmagazine` int(11) default NULL,
  `enquete` int(11) default NULL,
  `attributePlan` varchar(50) default NULL,
  `attributePlan_val` int(11) default NULL,
  `birthyear` int(11) default NULL,
  `month` int(11) default NULL,
  `date` int(11) default NULL,
  `sex_val` int(11) default NULL,
  `pref1` varchar(50) default NULL,
  `whichkn` varchar(50) default NULL,
  `question` text,
  `relation` varchar(50) default NULL,
  `age_val` varchar(50) default NULL,
  `situation` varchar(50) default NULL,
  `care_degree` varchar(50) default NULL,
  `ninchi` int(11) default NULL,
  `disease_name` text,
  `zipcode_2` int(11) default NULL,
  `zipcode_3` int(11) default NULL,
  `pref2` varchar(50) default NULL,
  `address1` text,
  `address2` text,
  `sikaku` text,
  `sikakuetc1` text,
  `sikakuetc2` text,
  `sikakuetc3` text,
  `sikakuetc4` text,
  `r_flag` int(11) default NULL,
  `flag` int(11) default NULL,
  `entryDay` date default NULL,
  `delete_flg` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`no`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `id` USING BTREE (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;